---
title: "About Me"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Bio

I grew up in New Jersey and completed my undergraduate career in sun-soaked Coral Gables, FL. I graduated from the University of Miami (Go 'Canes!) in May of 2021 with departmental honors and a Bachelor of Science in Psychology with minors in Art and Chemistry. After trekking across the country with [my adorable cat, Momo](momo.html), I served as a post-baccalaureate lab manager at the [Biology and Emotion of Addiction Via Experimental and Reproducible Science (BEAVERS) Laboratory](https://beaverslab.com/), part of the [School of Psychological Science at Oregon State University](https://catalog.oregonstate.edu/college-departments/liberal-arts/school-psychological-sciences/) in Corvallis, OR.

I am currently a second-year graduate student in the Counseling Psychology PhD program at [Colorado State University](https://psychology.colostate.edu/). I am working with Dr. Noah Emery, whose research centers around investigating the protective factors of positive affect in substance use in young people. With his counsel, I hope to learn more about conducting rigorous ecological momentary assessment (EMA) and intervention (EMI). I am looking forward to learning from all of the incredible faculty and graduate students in this program. 

As someone that values perspective and holds marginalized identities, I am incredibly passionate about diversity, equity and inclusion of all individuals in all spaces. I strive to create safe spaces of *acceptance* in each of my interactions. I am also an advocate of [open science practices](https://osf.io/) -- including reproducibility and transparency.

In my free time, I enjoy reading, creating art of many kinds, listening to music, walking in nature, practicing yoga, expressing gratitude and watching documentaries.

## Education

**M.S.** in Psychology | Colorado State University | Anticipated May 2025

**B.S.** in Psychology | University of Miami | 2021

## Interests

* Addiction and trauma research
* Emotional dysregulation
* Clinical work
* Mental health advocacy
* Open science
* Art creation
* Yoga and mindfulness
* Expanding my knowledge base
* Expressing gratitude
* Listening to music

## Skills
* Trilingual (English, Portuguese, Italian)
* R
* MATLAB and Neurobehavioral Systems Presentation programming
* Microsoft Office
* Adobe Acrobat, Photoshop and Illustrator
* Logo design

---

Distill is a publication format for scientific and technical writing, native to the web. 

Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.





